#include "morse.h"

// An associative array for morse symbols, horrendously done
// Indexing into morse can be done with the character of interest
// The size of the array is of course idiotically oversized
struct morse_symbol g_morse_table[MORSE_TABLE_LENGTH] = {
    ['A'] = {.code = ".-", .proficiency = 0},
    ['B'] = {.code = "-...", .proficiency = 0},
    ['C'] = {.code = "-.-.", .proficiency = 0},
    ['D'] = {.code = "-..", .proficiency = 0},
    ['E'] = {.code = ".", .proficiency = 0},
    ['F'] = {.code = "..-.", .proficiency = 0},
    ['G'] = {.code = "--.", .proficiency = 0},
    ['H'] = {.code = "....", .proficiency = 0},
    ['I'] = {.code = "..", .proficiency = 0},
    ['J'] = {.code = ".---", .proficiency = 0},
    ['K'] = {.code = "-.-", .proficiency = 0},
    ['L'] = {.code = ".-..", .proficiency = 0},
    ['M'] = {.code = "--", .proficiency = 0},
    ['N'] = {.code = "-.", .proficiency = 0},
    ['O'] = {.code = "---", .proficiency = 0},
    ['P'] = {.code = ".--.", .proficiency = 0},
    ['Q'] = {.code = "--.-", .proficiency = 0},
    ['R'] = {.code = ".-.", .proficiency = 0},
    ['S'] = {.code = "...", .proficiency = 0},
    ['T'] = {.code = "-", .proficiency = 0},
    ['U'] = {.code = "..-", .proficiency = 0},
    ['V'] = {.code = "...-", .proficiency = 0},
    ['W'] = {.code = ".--", .proficiency = 0},
    ['X'] = {.code = "-..-", .proficiency = 0},
    ['Y'] = {.code = "-.--", .proficiency = 0},
    ['Z'] = {.code = "--..", .proficiency = 0},
    ['0'] = {.code = "-----", .proficiency = 0},
    ['1'] = {.code = ".----", .proficiency = 0},
    ['2'] = {.code = "..---", .proficiency = 0},
    ['3'] = {.code = "...--", .proficiency = 0},
    ['4'] = {.code = "....-", .proficiency = 0},
    ['5'] = {.code = ".....", .proficiency = 0},
    ['6'] = {.code = "-....", .proficiency = 0},
    ['7'] = {.code = "--...", .proficiency = 0},
    ['8'] = {.code = "---..", .proficiency = 0},
    ['9'] = {.code = "----.", .proficiency = 0},
    ['.'] = {.code = ".-.-.-", .proficiency = 0},
    ['?'] = {.code = "..--..", .proficiency = 0},
};
